import { CountryConfig } from './types';

export const SUPPORTED_COUNTRIES: CountryConfig[] = [
  {
    countryCode: 'US',
    countryName: 'United States',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [10, 15, 20, 30],
    defaultInterestRate: 6.5,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly', 'biweekly', 'weekly'],
    minimumDownPaymentPct: 3,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 1.1,
    defaultHomeInsuranceRatePct: 0.4,
    taxCalculationMethod: 'percentage',
    mortgageInsuranceRules: {
      ltvThreshold: 80,
      annualRatePercentage: 0.75,
      appliesGlobally: false,
      minDownPaymentPct: 3,
    },
    mortgageTypes: [
      { id: 'us-30-fixed', name: '30-Year Fixed', termYears: 30, type: 'fixed', description: 'Fixed interest rate for the full 30-year term.' },
      { id: 'us-15-fixed', name: '15-Year Fixed', termYears: 15, type: 'fixed', description: 'Lower interest rate, higher monthly payment, paid off in half the time.' },
      { id: 'us-20-fixed', name: '20-Year Fixed', termYears: 20, type: 'fixed', description: 'Balanced option between 15-year and 30-year loans.' },
      { id: 'us-5-arm', name: '5/1 ARM', termYears: 30, type: 'arm', description: 'Fixed rate for the first 5 years, then adjusts annually.' },
    ],
    additionalFees: [{ name: 'Origination & Closing Costs', amount: 1.5, isPercentage: true }],
    supportedRateSources: ['Freddie Mac Primary Mortgage Market Survey', 'Bankrate Benchmark', 'User Input'],
    disclaimer: 'US mortgage estimates do not constitute official Loan Estimates or closing disclosures under TRID.',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    currencyCode: 'CAD',
    currencySymbol: '$',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 5.2,
    interestRateFrequency: 'semi-annual', // Canadian legal compounding requirement
    paymentFrequencyOptions: ['monthly', 'biweekly', 'weekly'],
    minimumDownPaymentPct: 5,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 0.85,
    defaultHomeInsuranceRatePct: 0.35,
    taxCalculationMethod: 'percentage',
    mortgageInsuranceRules: {
      ltvThreshold: 80, // CMHC default insurance required when down payment < 20%
      annualRatePercentage: 4.0, // CMHC premium added to loan amount or amortized
      appliesGlobally: false,
      minDownPaymentPct: 5,
    },
    mortgageTypes: [
      { id: 'ca-5-fixed', name: '5-Year Fixed Term (25yr Amortization)', termYears: 25, type: 'fixed', description: 'Rate locked for 5-year term with semi-annual compounding.' },
      { id: 'ca-3-fixed', name: '3-Year Fixed Term', termYears: 25, type: 'fixed', description: 'Popular short-term fixed rate contract.' },
      { id: 'ca-variable', name: '5-Year Variable', termYears: 25, type: 'variable', description: 'Fluctuates based on Prime rate changes.' },
    ],
    additionalFees: [{ name: 'Land Transfer Tax & Legal Fees', amount: 1.5, isPercentage: true }],
    supportedRateSources: ['Bank of Canada Rate Benchmarks', 'Canadian Major Banks', 'User Input'],
    disclaimer: 'Canadian mortgages compound semi-annually by law. CMHC mortgage default insurance applies for down payments below 20%.',
  },
  {
    countryCode: 'UK',
    countryName: 'United Kingdom',
    currencyCode: 'GBP',
    currencySymbol: '£',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [10, 15, 20, 25, 30, 35],
    defaultInterestRate: 4.8,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 5,
    maximumLoanTerm: 35,
    propertyTaxAvailable: true, // Council Tax / Stamp Duty
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.6,
    defaultHomeInsuranceRatePct: 0.25,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'uk-2-fixed', name: '2-Year Fixed Rate', termYears: 25, type: 'fixed', description: 'Fixed interest rate for initial 2 years.' },
      { id: 'uk-5-fixed', name: '5-Year Fixed Rate', termYears: 25, type: 'fixed', description: 'Rate locked for 5 years before switching to Standard Variable Rate (SVR).' },
      { id: 'uk-tracker', name: 'Tracker Mortgage', termYears: 25, type: 'tracker', description: 'Tracks Bank of England Base Rate plus a set percentage.' },
      { id: 'uk-variable', name: 'Standard Variable Rate (SVR)', termYears: 25, type: 'variable', description: 'Lender discretionary variable rate.' },
    ],
    additionalFees: [{ name: 'Stamp Duty Land Tax (SDLT)', amount: 2.0, isPercentage: true }],
    supportedRateSources: ['Bank of England Base Rate', 'FCA Regulated Lenders', 'User Input'],
    disclaimer: 'UK mortgages revert to Standard Variable Rate (SVR) after the initial fixed period unless remortgaged.',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    currencyCode: 'AUD',
    currencySymbol: '$',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 5.9,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly', 'biweekly', 'weekly'],
    minimumDownPaymentPct: 5,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Lenders Mortgage Insurance (LMI)
    defaultPropertyTaxRatePct: 0.5,
    defaultHomeInsuranceRatePct: 0.3,
    taxCalculationMethod: 'percentage',
    mortgageInsuranceRules: {
      ltvThreshold: 80, // LMI required if LTV > 80%
      annualRatePercentage: 1.5,
      appliesGlobally: false,
      minDownPaymentPct: 5,
    },
    mortgageTypes: [
      { id: 'au-variable', name: 'Variable Rate Mortgage', termYears: 30, type: 'variable', description: 'Most common Australian home loan, offers offset accounts.' },
      { id: 'au-3-fixed', name: '3-Year Fixed Rate', termYears: 30, type: 'fixed', description: 'Fixed rate period followed by variable rate.' },
      { id: 'au-split', name: 'Split Rate Loan (Fixed & Variable)', termYears: 30, type: 'fixed', description: 'Portion of loan fixed, remainder variable.' },
    ],
    additionalFees: [{ name: 'Stamp Duty & Conveyancing Fees', amount: 3.0, isPercentage: true }],
    supportedRateSources: ['Reserve Bank of Australia (RBA) Indicators', 'Big 4 Australian Banks', 'User Input'],
    disclaimer: 'Australian mortgages usually require Lenders Mortgage Insurance (LMI) when borrowing more than 80% LTV.',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    currencyCode: 'NZD',
    currencySymbol: '$',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 6.2,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly', 'biweekly', 'weekly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 0.4,
    defaultHomeInsuranceRatePct: 0.3,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'nz-2-fixed', name: '2-Year Fixed Term', termYears: 30, type: 'fixed', description: 'Popular NZ fixed rate term.' },
      { id: 'nz-floating', name: 'Floating Rate', termYears: 30, type: 'floating', description: 'Variable rate aligned with OCR changes.' },
    ],
    additionalFees: [],
    supportedRateSources: ['Reserve Bank of New Zealand (RBNZ)', 'User Input'],
    disclaimer: 'NZ reserve bank LVR restrictions govern minimum down payment requirements.',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30, 35],
    defaultInterestRate: 4.1,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 35,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Mortgage protection insurance mandatory
    defaultPropertyTaxRatePct: 0.2,
    defaultHomeInsuranceRatePct: 0.25,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'ie-5-fixed', name: '5-Year Fixed Rate', termYears: 30, type: 'fixed', description: 'Fixed period rate before variable SVR.' },
      { id: 'ie-variable', name: 'Variable Rate', termYears: 30, type: 'variable', description: 'Standard variable rate.' },
    ],
    additionalFees: [{ name: 'Stamp Duty & Legal Fees', amount: 1.0, isPercentage: true }],
    supportedRateSources: ['Central Bank of Ireland', 'User Input'],
    disclaimer: 'Central Bank of Ireland macroprudential rules require 10% minimum down payment for first-time buyers.',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 20,
    availableLoanTerms: [10, 15, 20, 25, 30],
    defaultInterestRate: 3.7,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.35,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'de-15-fixed', name: '10-15 Year Fixed Interest (Sollzinsbindung)', termYears: 20, type: 'fixed-period', description: 'Rate locked for 10-15 years (Sollzinsbindung) followed by refinancing.' },
      { id: 'de-20-fixed', name: '20-Year Fixed (Sollzinsbindung)', termYears: 20, type: 'fixed-period', description: 'Long-term rate stability.' },
    ],
    additionalFees: [{ name: 'Grunderwerbsteuer & Notary Fees', amount: 6.5, isPercentage: true }],
    supportedRateSources: ['Deutsche Bundesbank Indicators', 'User Input'],
    disclaimer: 'German mortgages specify a fixed interest period (Sollzinsbindung) after which remaining principal is refinanced (Anschlussfinanzierung).',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 20,
    availableLoanTerms: [10, 15, 20, 25],
    defaultInterestRate: 3.5,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 25,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Assurance Emprunteur (Mandatory Borrower Insurance)
    defaultPropertyTaxRatePct: 0.4,
    defaultHomeInsuranceRatePct: 0.25,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'fr-fixed', name: 'Fixed Rate (Prêt à Taux Fixe)', termYears: 20, type: 'fixed', description: 'Full term fixed interest rate with mandatory borrower insurance.' },
    ],
    additionalFees: [{ name: 'Frais de Notaire', amount: 7.5, isPercentage: true }],
    supportedRateSources: ['Banque de France Benchmarks', 'User Input'],
    disclaimer: 'French law caps debt ratio at 35% (HCSF rules) and mandates borrower insurance (Assurance Emprunteur).',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 3.4,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 20,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.5,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'es-fixed', name: 'Fixed Rate Mortgage (Hipoteca Fija)', termYears: 25, type: 'fixed', description: 'Constant interest rate throughout term.' },
      { id: 'es-variable', name: 'Euribor Variable (Hipoteca Variable)', termYears: 25, type: 'variable', description: 'Tied to 12-month Euribor + bank margin.' },
    ],
    additionalFees: [{ name: 'ITP Property Tax & Registry Fees', amount: 8.0, isPercentage: true }],
    supportedRateSources: ['Banco de España / Euribor Rate', 'User Input'],
    disclaimer: 'Spanish variable mortgages update annually based on Euribor 12-month rates.',
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 3.6,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 20,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.4,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'it-fixed', name: 'Fixed Rate (Mutuo Tasso Fisso)', termYears: 25, type: 'fixed', description: 'Constant monthly payment throughout loan.' },
      { id: 'it-variable', name: 'Variable Rate (Mutuo Tasso Variabile)', termYears: 25, type: 'variable', description: 'Linked to Euribor index.' },
    ],
    additionalFees: [{ name: 'Imposta Sostitutiva & Notary Fees', amount: 3.0, isPercentage: true }],
    supportedRateSources: ['Banca d’Italia', 'User Input'],
    disclaimer: 'Italian lenders restrict total loan payments to roughly one-third of net monthly income.',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 4.0,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 0, // Dutch mortgages allow up to 100% LTV
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // NHG (Nationale Hypotheek Garantie)
    defaultPropertyTaxRatePct: 0.15,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'nl-annuity', name: 'Annuity Mortgage (Annuïteitenhypotheek)', termYears: 30, type: 'fixed', description: 'Equal gross monthly payment, tax deductible interest.' },
      { id: 'nl-linear', name: 'Linear Mortgage (Lineaire Hypotheek)', termYears: 30, type: 'fixed', description: 'Equal principal payments each month; total payment decreases over time.' },
    ],
    additionalFees: [{ name: 'Overdrachtsbelasting (Transfer Tax)', amount: 2.0, isPercentage: true }],
    supportedRateSources: ['DNB / Dutch Mortgage Guarantee (NHG)', 'User Input'],
    disclaimer: 'Dutch mortgages qualify for mortgage interest tax deduction (Hypotheekrenteaftrek) under specific conditions.',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    currencyCode: 'CHF',
    currencySymbol: 'CHF',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 2.1,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly', 'quarterly'],
    minimumDownPaymentPct: 20,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.15,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'ch-fixed', name: '10-Year Fixed Mortgage', termYears: 30, type: 'fixed-period', description: 'Fixed rate locked for 10-year tranche.' },
      { id: 'ch-saron', name: 'SARON Flex Mortgage', termYears: 30, type: 'floating', description: 'Tied to Swiss Average Rate Overnight (SARON).' },
    ],
    additionalFees: [],
    supportedRateSources: ['Swiss National Bank (SNB)', 'User Input'],
    disclaimer: 'Swiss mortgages are structured in two tranches (1st mortgage up to 66.7% LTV never fully amortized; 2nd mortgage amortized).',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 3.9,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 20,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.2,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'at-fixed', name: 'Fixed Rate (Fixzinskredit)', termYears: 25, type: 'fixed', description: 'Fixed rate for agreed period.' },
      { id: 'at-variable', name: 'Variable Rate (Variabler Kredit)', termYears: 25, type: 'variable', description: 'Linked to Euribor rates.' },
    ],
    additionalFees: [{ name: 'Grunderwerbsteuer & Property Registration', amount: 4.6, isPercentage: true }],
    supportedRateSources: ['Oesterreichische Nationalbank', 'User Input'],
    disclaimer: 'FMA KIM-V regulations mandate 20% down payment and max 40% DTI ratio in Austria.',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 20,
    availableLoanTerms: [15, 20, 25],
    defaultInterestRate: 3.6,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 25,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 0.3,
    defaultHomeInsuranceRatePct: 0.25,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'be-fixed', name: 'Fixed Interest (Vaste Voet)', termYears: 20, type: 'fixed', description: 'Guaranteed rate for full term.' },
      { id: 'be-variable', name: 'Variable Interest (Variabele Voet)', termYears: 20, type: 'variable', description: 'Subject to legal cap limits.' },
    ],
    additionalFees: [{ name: 'Registration Rights & Notary', amount: 6.0, isPercentage: true }],
    supportedRateSources: ['National Bank of Belgium', 'User Input'],
    disclaimer: 'Belgian law limits how much variable mortgage rates can increase over time.',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 25, 30, 35, 40],
    defaultInterestRate: 3.8,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 40,
    propertyTaxAvailable: true, // IMI
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Life & Multi-risk insurance
    defaultPropertyTaxRatePct: 0.4,
    defaultHomeInsuranceRatePct: 0.25,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'pt-variable', name: 'Euribor Variable (Taxa Variável)', termYears: 30, type: 'variable', description: 'Most common mortgage type in Portugal.' },
      { id: 'pt-fixed', name: 'Fixed Rate (Taxa Fixa)', termYears: 30, type: 'fixed', description: 'Fixed interest for entire term.' },
    ],
    additionalFees: [{ name: 'IMT Property Tax & Stamp Duty', amount: 5.0, isPercentage: true }],
    supportedRateSources: ['Banco de Portugal Benchmarks', 'User Input'],
    disclaimer: 'Banco de Portugal guidelines enforce age-based maximum loan term limits.',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    currencyCode: 'INR',
    currencySymbol: '₹',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 20,
    availableLoanTerms: [5, 10, 15, 20, 25, 30],
    defaultInterestRate: 8.5,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.2,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'in-floating', name: 'Repo-Rate Linked Floating (EBLR)', termYears: 20, type: 'floating', description: 'Tied directly to RBI Repo Rate.' },
      { id: 'in-fixed', name: 'Fixed Rate Home Loan', termYears: 20, type: 'fixed', description: 'Fixed interest rate for set initial period.' },
    ],
    additionalFees: [{ name: 'Stamp Duty & Registration Fee', amount: 6.0, isPercentage: true }],
    supportedRateSources: ['Reserve Bank of India (RBI) Benchmarks', 'Major Indian Banks (SBI, HDFC, ICICI)', 'User Input'],
    disclaimer: 'Indian home loans calculate monthly payments using Equated Monthly Installment (EMI) formulas.',
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    currencyCode: 'NPR',
    currencySymbol: 'Rs.',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 15,
    availableLoanTerms: [5, 10, 15, 20, 25],
    defaultInterestRate: 10.5,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly', 'quarterly'],
    minimumDownPaymentPct: 30, // NRB requires 30% - 40% down payment (LTV 60%-70%)
    maximumLoanTerm: 25,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.1,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'np-base-linked', name: 'Base Rate Linked Floating Loan', termYears: 15, type: 'floating', description: 'Commercial Bank Base Rate + Premium margin.' },
      { id: 'np-fixed', name: 'Fixed Interest Home Loan', termYears: 15, type: 'fixed', description: 'Fixed interest rate for initial 3-5 year period.' },
    ],
    additionalFees: [{ name: 'Land Registration (Malpot) & Loan Management Fee', amount: 2.5, isPercentage: true }],
    supportedRateSources: ['Nepal Rastra Bank (NRB) Directives', 'Commercial Banks Base Rates', 'User Input'],
    disclaimer: 'Nepal Rastra Bank (NRB) directives mandate maximum 60% to 70% Loan-to-Value (LTV) limits on residential real estate loans.',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    currencyCode: 'AED',
    currencySymbol: 'AED',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [10, 15, 20, 25],
    defaultInterestRate: 4.9,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 20, // Central Bank of UAE 20% down for expats / 15% for UAE nationals
    maximumLoanTerm: 25,
    propertyTaxAvailable: false, // No recurring annual property tax in UAE
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 0,
    defaultHomeInsuranceRatePct: 0.2,
    taxCalculationMethod: 'manual',
    mortgageTypes: [
      { id: 'ae-3-fixed', name: '3-Year Fixed Rate', termYears: 25, type: 'fixed', description: 'Fixed interest for 3 years before reverting to EIBOR + margin.' },
      { id: 'ae-variable', name: 'EIBOR Variable Rate', termYears: 25, type: 'variable', description: 'Linked to Emirates Interbank Offered Rate.' },
    ],
    additionalFees: [{ name: 'Dubai Land Department (DLD) 4% Fee + Mortgage Registration', amount: 4.25, isPercentage: true }],
    supportedRateSources: ['Central Bank of the UAE / EIBOR', 'User Input'],
    disclaimer: 'CBUAE regulations mandate 20% minimum down payment for expatriates on first home purchases under AED 5 million.',
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    currencyCode: 'SGD',
    currencySymbol: 'S$',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 25,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 3.2,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 25, // MAS 75% LTV cap
    maximumLoanTerm: 30,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Home Protection Scheme (HPS) for HDB
    defaultPropertyTaxRatePct: 0.4,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'sg-sora', name: '3-Month SORA Floating Rate', termYears: 25, type: 'floating', description: 'Tied to Singapore Overnight Rate Average.' },
      { id: 'sg-fixed', name: '2-Year Fixed Rate', termYears: 25, type: 'fixed', description: 'Locked rate for initial 2 years.' },
    ],
    additionalFees: [{ name: 'Buyer Stamp Duty (BSD) & ABSD', amount: 3.0, isPercentage: true }],
    supportedRateSources: ['Monetary Authority of Singapore (MAS) / SORA', 'DBS / OCBC / UOB Benchmarks', 'User Input'],
    disclaimer: 'Monetary Authority of Singapore (MAS) restricts Total Debt Servicing Ratio (TDSR) to 55% of monthly income.',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    currencyCode: 'JPY',
    currencySymbol: '¥',
    currencyDecimalPlaces: 0, // JPY uses 0 decimal places
    defaultLoanTerm: 35,
    availableLoanTerms: [15, 20, 25, 30, 35],
    defaultInterestRate: 0.7, // Ultra low interest rates in Japan
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 35,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true, // Group Credit Life Insurance (Dansei)
    defaultPropertyTaxRatePct: 0.3,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'jp-variable', name: 'Variable Rate (変動金利)', termYears: 35, type: 'variable', description: 'Ultra-low variable rate tied to Short-term Prime Rate.' },
      { id: 'jp-flat35', name: 'Flat 35 Fixed Rate (フラット35)', termYears: 35, type: 'fixed', description: 'Government-backed 35-year full term fixed rate loan.' },
    ],
    additionalFees: [{ name: 'Registration License Tax & Agent Fees', amount: 3.0, isPercentage: true }],
    supportedRateSources: ['Bank of Japan (BOJ) Indicators', 'Japan Housing Finance Agency (JHF)', 'User Input'],
    disclaimer: 'Japanese home loans typically include mandatory Group Credit Life Insurance (団体信用生命保険 - Dansei).',
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    currencyCode: 'KRW',
    currencySymbol: '₩',
    currencyDecimalPlaces: 0, // KRW uses 0 decimal places
    defaultLoanTerm: 30,
    availableLoanTerms: [15, 20, 30, 40],
    defaultInterestRate: 4.2,
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 30, // DSR & LTV regulations
    maximumLoanTerm: 40,
    propertyTaxAvailable: true,
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: false,
    defaultPropertyTaxRatePct: 0.3,
    defaultHomeInsuranceRatePct: 0.15,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'kr-cofix', name: 'COFIX Floating Rate Mortgage', termYears: 30, type: 'floating', description: 'Tied to Cost of Funds Index (COFIX).' },
      { id: 'kr-fixed', name: 'Fixed Rate Mortgage', termYears: 30, type: 'fixed', description: 'Fixed interest rate term.' },
    ],
    additionalFees: [{ name: 'Acquisition Tax & Legal Registration', amount: 2.5, isPercentage: true }],
    supportedRateSources: ['Bank of Korea (BOK) / KFB COFIX', 'User Input'],
    disclaimer: 'Korean Financial Services Commission limits Debt Service Ratio (DSR) to 40% for banking sector loans.',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    currencyCode: 'ZAR',
    currencySymbol: 'R',
    currencyDecimalPlaces: 2,
    defaultLoanTerm: 20,
    availableLoanTerms: [15, 20, 25, 30],
    defaultInterestRate: 11.75, // Prime lending rate benchmark
    interestRateFrequency: 'annual',
    paymentFrequencyOptions: ['monthly'],
    minimumDownPaymentPct: 10,
    maximumLoanTerm: 30,
    propertyTaxAvailable: true, // Municipal Rates
    homeInsuranceAvailable: true,
    mortgageInsuranceAvailable: true,
    defaultPropertyTaxRatePct: 0.6,
    defaultHomeInsuranceRatePct: 0.3,
    taxCalculationMethod: 'percentage',
    mortgageTypes: [
      { id: 'za-prime-variable', name: 'Prime-Linked Variable Rate', termYears: 20, type: 'variable', description: 'Tied directly to SARB Repo / Commercial Prime Rate.' },
      { id: 'za-fixed', name: 'Fixed Rate Bond', termYears: 20, type: 'fixed', description: 'Fixed rate for agreed initial 1-5 year period.' },
    ],
    additionalFees: [{ name: 'Transfer Duty & Bond Registration Costs', amount: 4.5, isPercentage: true }],
    supportedRateSources: ['South African Reserve Bank (SARB) Prime Rate', 'Major SA Banks (Absa, FNB, Standard Bank)', 'User Input'],
    disclaimer: 'South African home loans (bonds) are traditionally linked to the South African Prime Lending Rate.',
  },
];
